### ISSUE TITLE
yii site design

### ISSUE THREAD

**Issue by allyraza** [ethercreative/yii2-ip-ratelimiter#7]
Hi there,

I see nice artwork on repo homepage seems like you know bit about design as well, I was wondering would you be able to give us a hand with yii2 home design.

here is what we have currently.

https://github.com/yiisoft-contrib/yiiframework.com

regards
Alrazi

**Comment by alexjcollins** [comment]
@allyraza Thanks for getting in touch.

I'd be glad to help out with the new yii2 site home page - do you have any particular issues/requests?
Would be good to get an idea of what you're looking for and then I can see where I might be able to best assist? 

Are you fine with working using Sketch files?

You can grab me at alex@ethercreative.co.uk, if that's easier?

Cheers

**Comment by allyraza** [comment]
@alexjcollins thank you for taking the time I really appreciate. 

I have few ideas, I see improvements can be made to the current design I have been putting together a list of urls just to get ideas that we can use on yii's new site. look at laravel's homepage for example see the design is really elegant they are making use of space very nicely as well as the typography helps make the design nice and good looking. please look at the links below.

http://laravel.com
really nice looking design.

https://dribbble.com/shots/3090809-Landing-page/attachments/652287
I found this to be attractive in terms of how they laid out the feature cards.

https://designmodo.com/slides/
this design has very elegant hero section and navigation is also nice

https://shopify.github.io/Timber/
I really like this for the docs scroll just below the hero you will see the docs section done very nicely.

perhaps we can adopt some of these ideas to put together a better design for yii's new site, lets see if we can contribute something back to the yii community. if you would like to discuss this further please let me know.

btw I am alrazi on yii forums in case you guys ever need assistance with anything yii related.

cheers

**Comment by alexjcollins** [comment]
@allyraza I just want to be sure that the people who will be making a decision with these kind of things in the yii community are aware of this request. I wouldn't like for us both to spend time and put effort into some work for it to not be used/required. Have you spoken to anyone on the core team?

As for your suggestions - I think they're good and certainly have a more visually engaging aesthetic.

Once we've figured out if they actually want us to suggest anything, I'd be happy to make a start on some ideas.

Cheers

**Comment by allyraza** [comment]
Hi Alex,

I am already discussing internally with the yii team to get a go ahead, will keep you posted.
