### ISSUE TITLE
Question about timePeriod

### ISSUE THREAD

**Issue by blacksmoke26** [ethercreative/yii2-ip-ratelimiter#8]
Can you please describe what is the `timePeriod` (unit) property? Seconds or what?

I mean `1 min` * `X seconds`?

**Comment by archlemon** [comment]
It is extending the Yii rate limiter, which I believe is in seconds.

**Comment by blacksmoke26** [comment]
Thank you, I also figure it out, It's `second` unit.

In your example, 600 means seconds = 10 mins.

`60` seconds * `10` minutes = `600` seconds
